# Numpy

In [1]:
import numpy as np

## Creating an Array

In [2]:
my_list = [1,2,3]
x = np.array(my_list)
x

array([1, 2, 3])

In [3]:
y = np.array([4,5,6])
y

array([4, 5, 6])

In [5]:
z = np.array([[1,2,3],[4,5,6]])
z

array([[1, 2, 3],
       [4, 5, 6]])

In [7]:
z.shape

(2, 3)

In [11]:
n = np.arange(0,30,2)
n

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [13]:
n.reshape(3,5)

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28]])

In [14]:
np.ones((3,2))

array([[ 1.,  1.],
       [ 1.,  1.],
       [ 1.,  1.]])

In [15]:
np.zeros((2,3))

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [16]:
np.eye(3)

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

In [17]:
np.diag(y)

array([[4, 0, 0],
       [0, 5, 0],
       [0, 0, 6]])

In [19]:
np.repeat([1,2,3],3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

In [21]:
p = np.ones([2,3],int)
p

array([[1, 1, 1],
       [1, 1, 1]])

In [23]:
np.vstack([p,2*p])

array([[1, 1, 1],
       [1, 1, 1],
       [2, 2, 2],
       [2, 2, 2]])

In [24]:
np.hstack([p,2*p])

array([[1, 1, 1, 2, 2, 2],
       [1, 1, 1, 2, 2, 2]])

In [25]:
a = np.array([-4,-2,-1,3,5])
a

array([-4, -2, -1,  3,  5])

In [26]:
a.sum()

1

In [27]:
a.max()

5

In [28]:
a.min()

-4

In [29]:
a.mean()

0.20000000000000001

In [30]:
a.std()

3.3105890714493698

In [31]:
a.argmax()

4

In [32]:
a.argmin()

0

# Indexing And Slicing

In [36]:
s = np.arange(13)**2
s

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144], dtype=int32)

In [37]:
s[0], s[4], s[0:3]

(0, 16, array([0, 1, 4], dtype=int32))

In [38]:
s[1:5]

array([ 1,  4,  9, 16], dtype=int32)

In [39]:
s[-4:]

array([ 81, 100, 121, 144], dtype=int32)

In [40]:
s[-5::-2]

array([64, 36, 16,  4,  0], dtype=int32)

In [42]:
r = np.arange(36)
r.resize((6,6))
r

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [43]:
r[2,2]

14

In [44]:
r[3,3:6]

array([21, 22, 23])

In [45]:
r[:2,:-1]

array([[ 0,  1,  2,  3,  4],
       [ 6,  7,  8,  9, 10]])

In [46]:
r[-1, ::2]

array([30, 32, 34])

In [48]:
r[r>30] = 30
r

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 30, 30, 30, 30, 30]])

## Iterating Over Arrays

In [49]:
test = np.random.randint(0,10,(4,3))
test

array([[4, 3, 1],
       [8, 0, 1],
       [0, 5, 4],
       [8, 7, 8]])

In [50]:
for row in test:
    print(row)

[4 3 1]
[8 0 1]
[0 5 4]
[8 7 8]


In [51]:
for i in range(len(test)):
    print(test[i])

[4 3 1]
[8 0 1]
[0 5 4]
[8 7 8]


In [52]:
type(lambda x:x+1)

function

In [53]:
a = np.random.randint(0,10,(6,6))
a

array([[3, 6, 0, 4, 2, 4],
       [8, 5, 0, 4, 7, 3],
       [1, 1, 1, 3, 7, 8],
       [6, 0, 4, 2, 4, 2],
       [0, 6, 9, 9, 8, 9],
       [3, 4, 1, 6, 6, 3]])

In [60]:
a.reshape(36)[::7]

array([3, 5, 1, 2, 8, 3])

In [62]:
a[2:4,2:4]

array([[1, 3],
       [4, 2]])